/*
  # Add Sample Posts for NGOs

  ## Posts Added
  - Volunteer drives for various causes
  - Donation needs for different categories
  - Real-world scenarios from Pune NGOs
*/

INSERT INTO public.posts (id, ngo_id, type, title, description, category, location, date_start, date_end, needed_count, status, images, view_count, created_at, updated_at) VALUES
  (
    'bbbbbbbb-1111-1111-1111-111111111111',
    'aaaaaaaa-1111-1111-1111-111111111111',
    'DRIVE',
    'Weekend Teaching Volunteers Needed',
    'The Akanksha Foundation is looking for passionate volunteers to teach underprivileged children on weekends. No prior teaching experience required. We provide training and support. Subjects include English, Math, Science, and Arts.',
    'Education',
    'Kothrud, Pune',
    CURRENT_DATE + INTERVAL '7 days',
    CURRENT_DATE + INTERVAL '90 days',
    20,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/8926544/pexels-photo-8926544.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/5905445/pexels-photo-5905445.jpeg?auto=compress&cs=tinysrgb&w=800'],
    45,
    NOW() - INTERVAL '2 days',
    NOW()
  ),
  (
    'bbbbbbbb-2222-2222-2222-222222222222',
    'aaaaaaaa-2222-2222-2222-222222222222',
    'DONATION',
    'Books and Stationery for Village Schools',
    'Swades Foundation is collecting books and stationery for village schools in rural Maharashtra. We need notebooks, textbooks, pens, pencils, geometry boxes, and educational charts. All items should be new or in good condition.',
    'Books',
    'Hadapsar, Pune',
    NULL,
    NULL,
    NULL,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=800'],
    128,
    NOW() - INTERVAL '5 days',
    NOW()
  ),
  (
    'bbbbbbbb-3333-3333-3333-333333333333',
    'aaaaaaaa-3333-3333-3333-333333333333',
    'DRIVE',
    'Skill Development Workshop Coordinators',
    'Pune City Connect is organizing skill development workshops for youth. We need volunteers with expertise in computer skills, spoken English, personality development, or vocational training to conduct sessions.',
    'Education',
    'Swargate, Pune',
    CURRENT_DATE + INTERVAL '14 days',
    CURRENT_DATE + INTERVAL '60 days',
    10,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800'],
    67,
    NOW() - INTERVAL '3 days',
    NOW()
  ),
  (
    'bbbbbbbb-4444-4444-4444-444444444444',
    'aaaaaaaa-4444-4444-4444-444444444444',
    'DRIVE',
    'Tree Plantation Drive in Sahyadri Hills',
    'Join us for a tree plantation drive in the Sahyadri hills. We will plant native species and work on reforestation. All necessary materials will be provided. Wear comfortable clothes and shoes suitable for outdoor activity.',
    'Environment',
    'Lavasa Road, Pune',
    CURRENT_DATE + INTERVAL '21 days',
    CURRENT_DATE + INTERVAL '21 days',
    50,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/1072824/pexels-photo-1072824.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg?auto=compress&cs=tinysrgb&w=800'],
    234,
    NOW() - INTERVAL '1 day',
    NOW()
  ),
  (
    'bbbbbbbb-5555-5555-5555-555555555555',
    'aaaaaaaa-5555-5555-5555-555555555555',
    'DONATION',
    'Medical Equipment and Medicines Needed',
    'Dilasa Trust is in urgent need of medical equipment and medicines for our mobile medical units. We require basic diagnostic equipment, first aid supplies, and commonly used medicines for rural health camps.',
    'Medical',
    'Kharadi, Pune',
    NULL,
    NULL,
    NULL,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/4386466/pexels-photo-4386466.jpeg?auto=compress&cs=tinysrgb&w=800'],
    89,
    NOW() - INTERVAL '4 days',
    NOW()
  ),
  (
    'bbbbbbbb-6666-6666-6666-666666666666',
    'aaaaaaaa-6666-6666-6666-666666666666',
    'DONATION',
    'Clothes and Toys for Children',
    'Snehalaya is collecting clothes and toys for children in our care homes. We need clothes for children aged 5-15 years, educational toys, books, and sports equipment. All items should be clean and in usable condition.',
    'Clothes',
    'Yerawada, Pune',
    NULL,
    NULL,
    NULL,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/5063382/pexels-photo-5063382.jpeg?auto=compress&cs=tinysrgb&w=800'],
    156,
    NOW() - INTERVAL '6 days',
    NOW()
  ),
  (
    'bbbbbbbb-7777-7777-7777-777777777777',
    'aaaaaaaa-7777-7777-7777-777777777777',
    'DRIVE',
    'Blood Donation Camp - Save Lives',
    'VNCT is organizing a blood donation camp. Healthy individuals aged 18-65 can donate blood. We follow all safety protocols. Each donation can save up to 3 lives. Light refreshments will be provided.',
    'Medical',
    'Shivajinagar, Pune',
    CURRENT_DATE + INTERVAL '10 days',
    CURRENT_DATE + INTERVAL '10 days',
    100,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/6823567/pexels-photo-6823567.jpeg?auto=compress&cs=tinysrgb&w=800'],
    312,
    NOW() - INTERVAL '2 days',
    NOW()
  ),
  (
    'bbbbbbbb-8888-8888-8888-888888888888',
    'aaaaaaaa-8888-8888-8888-888888888888',
    'DRIVE',
    'Scientific Awareness Campaign Volunteers',
    'MANS is conducting a scientific awareness campaign. We need volunteers to help with organizing events, creating awareness materials, and conducting street plays to promote rational thinking and scientific temper.',
    'Education',
    'Deccan Gymkhana, Pune',
    CURRENT_DATE + INTERVAL '28 days',
    CURRENT_DATE + INTERVAL '45 days',
    15,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=800'],
    78,
    NOW() - INTERVAL '1 day',
    NOW()
  ),
  (
    'bbbbbbbb-9999-9999-9999-999999999999',
    'aaaaaaaa-1111-1111-1111-111111111111',
    'DONATION',
    'Sports Equipment for Children',
    'Akanksha Foundation needs sports equipment for our after-school centers. We require footballs, cricket sets, badminton rackets, skipping ropes, and other sports items to promote physical education among children.',
    'Other',
    'Aundh, Pune',
    NULL,
    NULL,
    NULL,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/163487/baseball-bat-ball-baseball-equipment-163487.jpeg?auto=compress&cs=tinysrgb&w=800'],
    92,
    NOW() - INTERVAL '3 days',
    NOW()
  ),
  (
    'bbbbbbbb-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'aaaaaaaa-2222-2222-2222-222222222222',
    'DRIVE',
    'Digital Literacy Training Volunteers',
    'Help rural Maharashtra go digital! We need volunteers to teach basic computer skills and digital literacy to rural youth and women. Training includes internet basics, email, online forms, and digital payments.',
    'Technology',
    'Hinjewadi, Pune',
    CURRENT_DATE + INTERVAL '15 days',
    CURRENT_DATE + INTERVAL '75 days',
    12,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=800'],
    54,
    NOW() - INTERVAL '2 days',
    NOW()
  ),
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    'aaaaaaaa-4444-4444-4444-444444444444',
    'DONATION',
    'Rain Water Harvesting Materials',
    'Sahyadri Nisarga Mitra is implementing rain water harvesting systems in drought-prone villages. We need donations of pipes, storage tanks, filtration systems, and construction materials.',
    'Environment',
    'Mulshi, Pune',
    NULL,
    NULL,
    NULL,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg?auto=compress&cs=tinysrgb&w=800'],
    43,
    NOW() - INTERVAL '7 days',
    NOW()
  ),
  (
    'bbbbbbbb-cccc-cccc-cccc-cccccccccccc',
    'aaaaaaaa-6666-6666-6666-666666666666',
    'DRIVE',
    'Women Empowerment Workshop Facilitators',
    'Snehalaya is conducting empowerment workshops for women. We need volunteers to facilitate sessions on self-defense, financial literacy, legal rights, and entrepreneurship. Experience in social work preferred.',
    'Other',
    'Pimpri-Chinchwad, Pune',
    CURRENT_DATE + INTERVAL '20 days',
    CURRENT_DATE + INTERVAL '50 days',
    8,
    'OPEN',
    ARRAY['https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800'],
    71,
    NOW() - INTERVAL '4 days',
    NOW()
  )
ON CONFLICT (id) DO NOTHING;